### ISSUE TITLE
Unsupported docker-compose.yml

### ISSUE THREAD

**Issue by 1lastBr3ath** [GoSecure/jenkins-fsb#1]
When trying to run docker-compose, I keep getting the following error;
```
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
```
When changed to version "2" as asked in the error, nginx keeps throwing 502.

Tried on freshly installed Ubuntu and Debian.

**Comment by becojo** [comment]
It seems to be related to your `docker-compose` version. 

I was able build and run using the following version.

```
$ docker-compose -v
docker-compose version 1.17.1, build unknown
```

Which version are you using?

**Comment by 1lastBr3ath** [comment]
I'm using 1.8.0, default that came with `apt install docker-compose`. 
![docker-compose](https://user-images.githubusercontent.com/7494618/55710241-eaae2e80-5a09-11e9-842b-6016fddf38fa.png)

**Comment by becojo** [comment]
Try a manual install https://docs.docker.com/compose/install/

**Comment by 1lastBr3ath** [comment]
Thank you! Manual install seems to work after all.
